services:
  migrations:
    container_name: porfacan-migrations
    image: "${APP_IMAGE}"
    command: bash -c "python manage.py migrate && python manage.py collectstatic --noinput"
    volumes:
      - .:/app
    restart: "no"

  web:
    container_name: porfacan-web
    image: "${APP_IMAGE}"
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: unless-stopped

  celery-worker:
    container_name: porfacan-celery-worker
    image: "${APP_IMAGE}"
    command: celery -A config worker -l info
    volumes:
      - .:/app
    restart: unless-stopped

  celery-beat:
    container_name: porfacan-celery-beat
    image: "${APP_IMAGE}"
    command: celery -A config beat -l info
    volumes:
      - .:/app
    restart: unless-stopped

