echo APP_IMAGE=$APP_IMAGE  >> .env
echo PROXY_IMAGE=$PROXY_IMAGE  >> .env
echo CI_REGISTRY_USER=$CI_REGISTRY_USER   >> .env
echo CI_JOB_TOKEN=$CI_JOB_TOKEN  >> .env
echo CI_REGISTRY=$CI_REGISTRY >> .env
echo GUNICORN_WORKERS=$GUNICORN_WORKERS  >> .env
