# Generated by Django 5.2.12 on 2026-03-14 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('archiver', '0001_initial'),
        ('lexicon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archiverecord',
            name='definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archive_records', to='lexicon.definition'),
        ),
        migrations.AddIndex(
            model_name='archiverecord',
            index=models.Index(fields=['status', '-created_at'], name='archiver_ar_status_b1aef6_idx'),
        ),
        migrations.AddIndex(
            model_name='archiverecord',
            index=models.Index(fields=['source_url'], name='archiver_ar_source__7af822_idx'),
        ),
    ]
