# Generated by Django 5.2.12 on 2026-03-14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archiver", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="archiverecord",
            name="file_hash",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="archiverecord",
            name="is_source_available",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="archiverecord",
            name="last_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="archiverecord",
            name="link_rot_flagged_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="archiverecord",
            name="verification_error",
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
