# Generated by Django 5.2.12 on 2026-03-15 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiver', '0004_archiverecord_verbose_names_i18n'),
        ('lexicon', '0009_alter_definition_author_alter_definition_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archiverecord',
            name='arweave_hash',
            field=models.CharField(blank=True, max_length=200, verbose_name='Arweave hash'),
        ),
        migrations.AlterField(
            model_name='archiverecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='archiverecord',
            name='definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archive_records', to='lexicon.definition', verbose_name='Definition'),
        ),
        migrations.AlterField(
            model_name='archiverecord',
            name='file_hash',
            field=models.CharField(blank=True, max_length=128, verbose_name='File hash'),
        ),
        migrations.AlterField(
            model_name='archiverecord',
            name='is_source_available',
            field=models.BooleanField(default=True, verbose_name='Is source available'),
        ),
        migrations.AlterField(
            model_name='archiverecord',
            name='last_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last verified at'),
        ),
        migrations.AlterField(
            model_name='archiverecord',
            name='link_rot_flagged_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Link rot flagged at'),
        ),
        migrations.AlterField(
            model_name='archiverecord',
            name='s3_path',
            field=models.CharField(blank=True, max_length=500, verbose_name='S3 path'),
        ),
        migrations.AlterField(
            model_name='archiverecord',
            name='snapshot_type',
            field=models.CharField(choices=[('screenshot', 'Screenshot'), ('html', 'HTML')], default='screenshot', max_length=20, verbose_name='Snapshot type'),
        ),
        migrations.AlterField(
            model_name='archiverecord',
            name='source_url',
            field=models.URLField(verbose_name='Source URL'),
        ),
        migrations.AlterField(
            model_name='archiverecord',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='archiverecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='archiverecord',
            name='verification_error',
            field=models.CharField(blank=True, max_length=300, verbose_name='Verification error'),
        ),
    ]
