# Generated by Django 5.2.12 on 2026-03-15 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_verbose_names_i18n'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='reputation_iq',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Reputation IQ'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('visitor', 'Visitor'), ('contributor', 'Contributor'), ('editor', 'Editor'), ('moderator', 'Moderator'), ('admin', 'Admin')], db_index=True, default='visitor', max_length=20, verbose_name='Role'),
        ),
    ]
