# Generated by Django 5.2.12 on 2026-03-14 16:27

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lexicon', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='definition',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='definitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='definition',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definitions', to='lexicon.entry'),
        ),
        migrations.AddField(
            model_name='entry',
            name='epoch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='lexicon.epoch'),
        ),
        migrations.AddIndex(
            model_name='definition',
            index=models.Index(fields=['entry', '-created_at'], name='lexicon_def_entry_i_295716_idx'),
        ),
        migrations.AddIndex(
            model_name='definition',
            index=models.Index(fields=['upvotes', 'downvotes'], name='lexicon_def_upvotes_9f213e_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='lexicon_ent_search__b88a45_gin'),
        ),
    ]
