# Generated by Django 5.2.12 on 2026-03-14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lexicon", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="etymology",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="definition",
            name="hot_score_value",
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AlterModelOptions(
            name="definition",
            options={"ordering": ["-hot_score_value", "-created_at"]},
        ),
        migrations.AddIndex(
            model_name="definition",
            index=models.Index(fields=["hot_score_value"], name="lexicon_def_hot_sco_e6e4ce_idx"),
        ),
        migrations.CreateModel(
            name="DefinitionVote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "value",
                    models.SmallIntegerField(choices=[(-1, "Downvote"), (1, "Upvote")]),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="lexicon.definition",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="definition_votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("definition", "user")},
            },
        ),
        migrations.AddIndex(
            model_name="definitionvote",
            index=models.Index(fields=["definition", "value"], name="lexicon_def_definit_d92044_idx"),
        ),
    ]
