# Generated by Django 5.2.12 on 2026-03-15

from django.contrib.postgres.indexes import GinIndex
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lexicon", "0003_entry_etymology_definitionvote_and_more"),
    ]

    operations = [
        TrigramExtension(),
        migrations.AddIndex(
            model_name="entry",
            index=GinIndex(
                fields=["headword"],
                opclasses=["gin_trgm_ops"],
                name="lexicon_ent_headword_trgm",
            ),
        ),
    ]
