# Generated by Django 5.2.12 on 2026-03-14 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0003_entry_etymology_definitionvote_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='definition',
            new_name='lexicon_def_hot_sco_c485e6_idx',
            old_name='lexicon_def_hot_sco_e6e4ce_idx',
        ),
        migrations.RenameIndex(
            model_name='definitionvote',
            new_name='lexicon_def_definit_82cb69_idx',
            old_name='lexicon_def_definit_d92044_idx',
        ),
    ]
