# Generated by Django 5.2.12 on 2026-03-15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lexicon", "0005_trigram_search_support"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="slug",
            field=models.SlugField(allow_unicode=True, max_length=255, unique=True),
        ),
    ]
