# Generated by Django 5.2.12 on 2026-03-15 20:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0007_definitionattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='definition',
            options={'ordering': ['-hot_score_value', '-created_at'], 'verbose_name': 'Definition', 'verbose_name_plural': 'Definitions'},
        ),
        migrations.AlterModelOptions(
            name='definitionattachment',
            options={'ordering': ['created_at'], 'verbose_name': 'Definition attachment', 'verbose_name_plural': 'Definition attachments'},
        ),
        migrations.AlterModelOptions(
            name='definitionvote',
            options={'verbose_name': 'Definition vote', 'verbose_name_plural': 'Definition votes'},
        ),
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-created_at'], 'verbose_name': 'Entry', 'verbose_name_plural': 'Entries'},
        ),
        migrations.AlterModelOptions(
            name='epoch',
            options={'ordering': ['start_date'], 'verbose_name': 'Epoch', 'verbose_name_plural': 'Epochs'},
        ),
        migrations.RemoveConstraint(
            model_name='definitionattachment',
            name='lexicon_attachment_link_or_image_required',
        ),
        migrations.AddConstraint(
            model_name='definitionattachment',
            constraint=models.CheckConstraint(condition=models.Q(('link', ''), ('image', ''), _negated=True), name='lexicon_attachment_link_or_image_required'),
        ),
    ]
