# Generated by Django 5.2.12 on 2026-03-15 21:37

import django.contrib.postgres.search
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0008_alter_definition_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='definition',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='definitions', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='definition',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='definition',
            name='context_annotation',
            field=models.TextField(blank=True, verbose_name='Context annotation'),
        ),
        migrations.AlterField(
            model_name='definition',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='definition',
            name='downvotes',
            field=models.PositiveIntegerField(default=0, verbose_name='Downvotes'),
        ),
        migrations.AlterField(
            model_name='definition',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definitions', to='lexicon.entry', verbose_name='Entry'),
        ),
        migrations.AlterField(
            model_name='definition',
            name='hot_score_value',
            field=models.FloatField(db_index=True, default=0.0, verbose_name='Hot score value'),
        ),
        migrations.AlterField(
            model_name='definition',
            name='reputation_score',
            field=models.IntegerField(default=0, verbose_name='Reputation score'),
        ),
        migrations.AlterField(
            model_name='definition',
            name='upvotes',
            field=models.PositiveIntegerField(default=0, verbose_name='Upvotes'),
        ),
        migrations.AlterField(
            model_name='definitionattachment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='definitionattachment',
            name='definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='lexicon.definition', verbose_name='Definition'),
        ),
        migrations.AlterField(
            model_name='definitionattachment',
            name='image',
            field=models.ImageField(blank=True, upload_to='lexicon/definition_attachments/%Y/%m/%d', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='definitionattachment',
            name='link',
            field=models.URLField(blank=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='definitionvote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='definitionvote',
            name='definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='lexicon.definition', verbose_name='Definition'),
        ),
        migrations.AlterField(
            model_name='definitionvote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='definitionvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definition_votes', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='definitionvote',
            name='value',
            field=models.SmallIntegerField(choices=[(-1, 'Downvote'), (1, 'Upvote')], verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='epoch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='lexicon.epoch', verbose_name='Epoch'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='etymology',
            field=models.TextField(blank=True, verbose_name='Etymology'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='headword',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Headword'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Is verified'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True, verbose_name='Search vector'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='epoch',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='epoch',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='epoch',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='epoch',
            name='start_date',
            field=models.DateField(verbose_name='Start date'),
        ),
    ]
