# Generated by Django 5.2.12 on 2026-03-25 13:33

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0014_definition_is_featured'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='definition',
            options={'ordering': ['-is_featured', '-hot_score_value', '-created_at'], 'verbose_name': 'Definition', 'verbose_name_plural': 'Definitions'},
        ),
        migrations.AlterField(
            model_name='entry',
            name='description',
            field=models.TextField(blank=True, help_text='A short description of the entry, this will be only visible to admins to know the context of the entry.', max_length=1024, verbose_name='Description'),
        ),
        migrations.AddIndex(
            model_name='definition',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.search.SearchVector('content', 'context_annotation', config='simple'), name='lexicon_def_search_vector_gin'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['is_verified', '-created_at'], name='lex_ent_ver_cr_idx'),
        ),
        migrations.RunSQL(
            sql=(
                "UPDATE lexicon_entry "
                "SET search_vector = to_tsvector('simple', COALESCE(headword, ''))"
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
