# Generated by Django 5.2.12 on 2026-03-25 14:12

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0015_alter_definition_options_alter_entry_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(django.contrib.postgres.indexes.OpClass('headword', name='varchar_pattern_ops'), name='lex_ent_head_prefix_idx'),
        ),
    ]
