# Generated by Django 5.2.12 on 2026-03-27 01:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0017_similar_entry_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='definition',
            options={'ordering': ['-is_featured', '-hot_score_value', 'created_at'], 'verbose_name': 'Definition', 'verbose_name_plural': 'Definitions'},
        ),
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['headword'], 'verbose_name': 'Entry', 'verbose_name_plural': 'Entries'},
        ),
        migrations.RemoveIndex(
            model_name='definition',
            name='lexicon_def_entry_i_295716_idx',
        ),
        migrations.RemoveIndex(
            model_name='entry',
            name='lex_ent_ver_cr_idx',
        ),
        migrations.AddIndex(
            model_name='definition',
            index=models.Index(fields=['entry', 'created_at'], name='lexicon_def_entry_i_f92c42_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['is_verified', 'headword'], name='lex_ent_ver_cr_idx'),
        ),
    ]
