# Generated by Django 5.2.12 on 2026-04-04 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0023_definition_is_ai_generated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='epochs',
            field=models.ManyToManyField(blank=True, help_text='Epochs that the entry belongs to. This is only visible to admins.', related_name='entries', to='lexicon.epoch', verbose_name='Epochs'),
        ),
    ]
