# Generated by Django 5.2.12 on 2026-04-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0024_alter_entry_epochs'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, help_text='Highlight this entry on the public list. Only editable in the admin site.', verbose_name='Featured'),
        ),
    ]
