# Generated by Django 5.2.12 on 2026-04-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('lexicon', '0025_entry_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='visible_to_groups',
            field=models.ManyToManyField(blank=True, help_text='Leave empty for all visitors. If you select groups, only logged-in users in at least one of those groups (plus staff) see this page in the menu and can open it.', related_name='lexicon_pages', to='auth.group', verbose_name='Visible only to groups'),
        ),
    ]
