# Generated by Django 5.2.12 on 2026-04-03 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='entryaidraftjob',
            new_name='ai_entryaid_user_id_321bd1_idx',
            old_name='ai_entryaidr_user_id_665f8c_idx',
        ),
        migrations.RenameIndex(
            model_name='entryaidraftjob',
            new_name='ai_entryaid_status_fb1ae1_idx',
            old_name='ai_entryaidr_status_a47345_idx',
        ),
    ]
