name: Test

on:
  pull_request:

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup local settings
        run: |
          mkdir -p envs
          cp envs.example/settings.py envs/settings.py

      - name: Run tests
        run: docker compose -f docker-compose-ci.yml run --rm web pytest

      - name: Cleanup
        if: always()
        run: |
          rm -f envs/settings.py
          rm -f ~/.ssh/id_rsa

