name: Test

on:
  pull_request:

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup local settings override
        run: |
          mkdir -p envs
          cp envs.example/settings.py envs/settings.py

      - name: Run tests
        run: docker compose -f docker-compose.yml run --rm web pytest

      - name: Cleanup settings override
        if: always()
        run: |
          docker compose -f docker-compose.yml down -v --remove-orphans
          rm -f envs/settings.py
